name: Server - Linux

on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: actions/checkout
        with:
          fetch-depth: 0
          submodules: recursive
      - name: update apt
        run: sudo apt update & sudo apt-get upgrade -y
      - name: install dependencies
        run: sudo apt-get install -y build-essential g++ python-dev autotools-dev libboost-all-dev libssl-dev libicu-dev libbz2-dev cmake git screen
      - name: build server
        run: |
          mkdir build && cd build
          cmake -D STATIC=true -D ARCH=x86-64 -D CMAKE_BUILD_TYPE=Release ..
          make -j2 daemon simplewallet
      - name: Tar files
        run: cd build/src && tar -cvf ../../server-linux-amd64.tar evoxd simplewallet
      - uses: actions/upload-artifact@v3
        with:
          name: server-linux-amd64
          if-no-files-found: error
          path: server-linux-amd64.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          generate_release_notes: true
          files: ${{ github.workspace }}/server-linux-amd64.tar