name: Server - Linux

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt-get install -y build-essential g++ python-dev autotools-dev libboost-all-dev libssl-dev libicu-dev libbz2-dev cmake git screen checkinstall zlib1g-dev
      - name: install dependencies GUI
        run: |
              chmod +x dependencies.sh && ./dependencies.sh
      - name: build server
        run: |
              utils/build_script_linux.sh
      - name: Tar files
        run: cd build/src && tar -cvf ../../server-linux-amd64.tar evoxd simplewallet
      - uses: actions/upload-artifact@v3
        with:
          name: server-linux-amd64
          if-no-files-found: error
          path: server-linux-amd64.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          generate_release_notes: true
          files: ${{ github.workspace }}/server-linux-amd64.tar